
// ----------- IMPORTACIONES -----------
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Footer from "./components/footer";

// ----------- FUENTE MANROPE -----------
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ----------- LAYOUT GLOBAL -----------
  // Incluye navegación y footer en todas las páginas
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased bg-black text-white`}>
        <Nav />
        <main className="container mx-auto min-h-screen max-w-6xl sm:p-8 text-white">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
